site_name: Cardano MPFS Browser
site_url: https://lambdasistemi.github.io/cardano-mpfs-browser/
repo_url: https://github.com/lambdasistemi/cardano-mpfs-browser
repo_name: lambdasistemi/cardano-mpfs-browser

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Design: design.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - admonition

extra_javascript:
  - https://cdn.jsdelivr.net/gh/paolino/dev-assets@55d2de7/mkdocs/docs/js/read-aloud.js
