site_name: Cardano MPFS Browser
site_url: https://lambdasistemi.github.io/cardano-mpfs-browser/
repo_url: https://github.com/lambdasistemi/cardano-mpfs-browser
repo_name: lambdasistemi/cardano-mpfs-browser

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Design: design.md

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight
  - tables
  - admonition
